name: Build and Publish release

on:
  release:
    types: [published]
    
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag (e.g., v1.0.0)'
        required: true

env:
  RELEASE_TAG: ${{ github.event.inputs.tag || github.ref_name }}
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Decode Keystore
      run: |
        echo "${{ secrets.SIGNING_KEY }}" | base64 -d > keystore.jks
        chmod 644 keystore.jks
    
    - name: Generate keystore.properties
      run: |
        KEYSTORE_PATH="$GITHUB_WORKSPACE/keystore.jks"
        echo "Keystore file: $KEYSTORE_PATH"
        echo "storeFile=$KEYSTORE_PATH" > keystore.properties
        echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.ALIAS }}" >> keystore.properties
    
    - name: Build APK
      run: |
        ./gradlew assembleGoogleRelease
    
    - name: Generate Changelog
      run: |
        ./gradlew generateReleaseChangeLog
    
    - name: Rename APK
      run: |
        mv app/build/outputs/apk/google/release/app-google-release.apk \
           app/build/outputs/apk/google/release/${{ vars.BUILD_NAME }}.FOSS.v${{ env.RELEASE_TAG }}.apk

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Release ${{ env.RELEASE_TAG }}
        body_path: app/build/outputs/changelog/changelog.txt
        files: |
          app/build/outputs/apk/google/release/${{ vars.BUILD_NAME }}.FOSS.v${{ env.RELEASE_TAG }}.apk
